# Generated by Django 5.1.2 on 2024-10-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Ожидает", "ожидает"),
                    ("подтвержден", "Подтвержден"),
                    ("отменен", "Отменен"),
                ],
                default="Ожидает",
                max_length=12,
                verbose_name="Статус",
            ),
        ),
    ]
