# Generated by Django 5.1.2 on 2024-10-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, verbose_name="сумма"
            ),
        ),
    ]
